- name: Reboot
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true

- name: "lldpd restarted"
  become: True
  systemd:
    name: lldpd.service
    state: restarted
